---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 3.1 Set Daemon umask (Scored)
    lineinfile: >
      dest=/etc/sysconfig/init
      state=present
      regexp=^umask
      line="umask 027"
    when: ansible_distribution == "RedHat"
    tags:
      - scored
      - section3.1

  - name: 3.2 Remove X Windows (runlevel 3) (Scored)
    lineinfile: >
      dest=/etc/inittab
      state=present
      regexp="^id:"
      line="id:3:initdefault:"
    when: ansible_distribution == "RedHat"
    tags:
      - scored
      - section3.2

  - name: 3.2 Remove X Windows (remove package group) (Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - xserver-xorg
    tags:
      - scored
      - section3.2

  - name: 3.3 Disable Avahi Server (check if installed) (Scored)
    stat: path=/etc/init.d/avahi-daemon
    register: avahi_service
    tags:
      - scored
      - section3.3

  - name: 3.3 Disable Avahi Server (disable service) (Scored)
    service: >
      name=avahi-daemon
      state=stopped
      enabled=no
    when: avahi_service.stat.exists
    tags:
      - scored
      - section3.3

  - name: 3.4 Check to see if cups daemon is installed (Not Scored)
    stat: path=/etc/init.d/cups
    register: cups_service
    tags:
      - notscored
      - section3.4

  - name: 3.4 Disable Print Server - CUPS (Not Scored)
    service: >
      name=cups
      state=stopped
      enabled=no
    ignore_errors: yes
    when: cups_service.stat.exists
    tags:
      - notscored
      - section3.4

  - name: 3.5 Remove DHCP Server (Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - isc-dhcp-server
    tags:
      - scored
      - section3.5

  - name: 3.6 Configure Network Time Protocol (ipv4) (Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - ntp
    always_run: yes
    tags:
      - scored
      - section3.6

  - name: 3.6 Configure Network Time Protocol (ipv4) (Scored)
    service: >
      name=ntp
      state=started
      enabled=yes
    tags:
      - scored
      - section3.6

  - name: 3.6 Configure Network Time Protocol (ipv4) (Scored)
    lineinfile: >
      dest=/etc/ntp.conf
      state=present
      regexp="^restrict default"
      line="restrict default kod nomodify notrap nopeer noquery"
      insertafter=EOF
    tags:
      - scored
      - section3.6

  - name: 3.6 Configure Network Time Protocol (ipv6) (Scored)
    lineinfile: >
      dest=/etc/ntp.conf
      state=present
      regexp="^restrict -6 default"
      line="restrict -6 default kod nomodify notrap nopeer noquery"
      insertafter=EOF
    tags:
      - scored
      - section3.6

  - name: 3.7 Remove LDAP (Not Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - openldap-clients
    when: not ldap_client and ansible_distribution == "RedHat"
    tags:
      - notscored
      - section3.7

  - name: 3.7 Remove LDAP (Not Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - slapd
    when: not ldap_server
    tags:
      - notscored
      - section3.7

  - name: 3.8 Disable NFS and RPC (check for nfs-utils) (Not Scored)
    stat: path=/etc/init.d/nfslock
    register: nfs_utils
    tags:
      - notscored
      - section3.8

  - name: 3.8 Disable NFS and RPC (check for rpcbind) (Not Scored)
    stat: path=/etc/init.d/rpcbind
    register: rpcbind
    tags:
      - notscored
      - section3.8

  - name: 3.8 Disable NFS and RPC (nfs-utils services) (Not Scored)
    service: >
      name={{ item }}
      state=stopped
      enabled=no
    with_items:
      - nfslock
      - rpcgssd
      - rpcidmapd
      - rpcsvcgssd
    when: nfs_utils.stat.exists
    tags:
      - notscored
      - section3.8

  - name: 3.8 Disable NFS and RPC (rpcbind services) (Not Scored)
    service: >
      name=rpcbind
      state=stopped
      enabled=no
    when:
      - rpcbind.stat.exists
      - not nfs
    tags:
      - notscored
      - section3.8

  - name: 3.9 Remove DNS Server (Not Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - bind9
    when: not dns
    tags:
      - notscored
      - section3.9

  - name: 3.10 Remove FTP Server (Not Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - vsftpd
    when: not ftp
    tags:
      - notscored
      - section3.10

  - name: 3.11 Remove HTTP Server (Not Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - apache2
    when: not httpd
    tags:
      - notscored
      - section3.11

  - name: 3.12 Remove Dovecot (IMAP and POP3 services) (Not Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
        - dovecot-core
    when: not dovecot
    tags:
      - notscored
      - section3.12

  - name: 3.13 Remove Samba (Not Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - samba
    when: not samba
    tags:
      - notscored
      - section3.13

  - name: 3.14 Remove HTTP Proxy Server (Not Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - squid
    when: not squid
    tags:
      - notscored
      - section3.14

  - name: 3.15 Remove SNMP Server (Not Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - snmpd
    when: not snmp
    tags:
      - notscored
      - section3.15

  - name: 3.16 Configure Mail Transfer Agent for Local-Only Mode (Scored)
    action: "{{os_packager}} name={{item}}"
    with_items:
      - postfix
    tags:
      - scored
      - section3.16

  - name: 3.16 Configure Mail Transfer Agent for Local-Only Mode (Scored)
    lineinfile: >
      backup=yes 
      state=present 
      dest=/etc/postfix/main.cf
      backrefs=yes
      regexp="^inet_interfaces"
      line="inet_interfaces = localhost"
    ignore_errors: yes
    tags:
      - scored
      - section3.16
